package de.nexus.agent.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val NexusPrimary = Color(0xFF1565C0)
val NexusOnPrimary = Color(0xFFFFFFFF)
val NexusPrimaryContainer = Color(0xFFD1E4FF)
val NexusOnPrimaryContainer = Color(0xFF001D36)
val NexusSecondary = Color(0xFF535F70)
val NexusOnSecondary = Color(0xFFFFFFFF)
val NexusSecondaryContainer = Color(0xFFD7E3F7)
val NexusOnSecondaryContainer = Color(0xFF101C2B)
val NexusTertiary = Color(0xFF6B5778)
val NexusOnTertiary = Color(0xFFFFFFFF)
val NexusTertiaryContainer = Color(0xFFF2DAFF)
val NexusOnTertiaryContainer = Color(0xFF251431)
val NexusError = Color(0xFFBA1A1A)
val NexusOnError = Color(0xFFFFFFFF)
val NexusErrorContainer = Color(0xFFFFDAD6)
val NexusOnErrorContainer = Color(0xFF410002)
val NexusBackgroundLight = Color(0xFFFDFBFF)
val NexusOnBackgroundLight = Color(0xFF1A1C1E)
val NexusSurfaceLight = Color(0xFFFDFBFF)
val NexusOnSurfaceLight = Color(0xFF1A1C1E)
val NexusSurfaceVariantLight = Color(0xFFDFE2EB)
val NexusOnSurfaceVariantLight = Color(0xFF43474E)
val NexusOutlineLight = Color(0xFF73777F)
val NexusOutlineVariantLight = Color(0xFFC3C7CF)
val NexusSurfaceTintLight = Color(0xFF1565C0)

// Dark theme colors
val NexusDarkPrimary = Color(0xFF9ECAFF)
val NexusDarkOnPrimary = Color(0xFF003258)
val NexusDarkPrimaryContainer = Color(0xFF00497D)
val NexusDarkOnPrimaryContainer = Color(0xFFD1E4FF)
val NexusDarkSecondary = Color(0xFFBBC7DB)
val NexusDarkOnSecondary = Color(0xFF253140)
val NexusDarkSecondaryContainer = Color(0xFF3B4858)
val NexusDarkOnSecondaryContainer = Color(0xFFD7E3F7)
val NexusDarkTertiary = Color(0xFFD6BEE4)
val NexusDarkOnTertiary = Color(0xFF3B2948)
val NexusDarkTertiaryContainer = Color(0xFF523F5F)
val NexusDarkOnTertiaryContainer = Color(0xFFF2DAFF)
val NexusDarkError = Color(0xFFFFB4AB)
val NexusDarkOnError = Color(0xFF690005)
val NexusDarkErrorContainer = Color(0xFF93000A)
val NexusDarkOnErrorContainer = Color(0xFFFFDAD6)
val NexusBackgroundDark = Color(0xFF1A1C1E)
val NexusOnBackgroundDark = Color(0xFFE2E2E6)
val NexusSurfaceDark = Color(0xFF1A1C1E)
val NexusOnSurfaceDark = Color(0xFFE2E2E6)
val NexusSurfaceVariantDark = Color(0xFF43474E)
val NexusOnSurfaceVariantDark = Color(0xFFC3C7CF)
val NexusOutlineDark = Color(0xFF8D9199)
val NexusOutlineVariantDark = Color(0xFF43474E)
val NexusSurfaceTintDark = Color(0xFF9ECAFF)

// Shapes
val NexusShapes = androidx.compose.material3.Shapes()
